apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Chart.Name}}-create-configmap-{{.Release.Name}}"
  labels:
    app: bluecompute
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "21"
spec:
  template:
    metadata:
      name: "{{.Chart.Name}}-create-configmap-{{.Release.Name}}"
      labels:
        app: bluecompute
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
      - name: create-configmap
        image: ibmcase/kubectl:latest
        command: [ "/bin/bash", "-c" ]
        args: ["kubectl get configmaps bluemix-target --namespace {{ .Release.Namespace }} || \
        kubectl create configmap bluemix-target \ 
        --from-literal=bluemix-api-endpoint=${BLUEMIX_API_ENDPOINT} \
        --from-literal=bluemix-org=${BLUEMIX_ORG} \
        --from-literal=bluemix-space=${BLUEMIX_SPACE} \
        --from-literal=bluemix-registry=${BLUEMIX_REGISTRY} \
        --from-literal=bluemix-registry-namespace=${BLUEMIX_REGISTRY_NAMESPACE} \
        --from-literal=kube-cluster-name=${KUBE_CLUSTER_NAME} \
        --namespace {{ .Release.Namespace }}"]
        imagePullPolicy: IfNotPresent
        env:
        - name: BLUEMIX_API_ENDPOINT
          value: {{ .Values.configMap.bluemixAPIEndpoint }}
        - name: BLUEMIX_ORG
          value: {{ .Values.configMap.bluemixOrg }}
        - name: BLUEMIX_SPACE
          value: {{ .Values.configMap.bluemixSpace }}
        - name: BLUEMIX_REGISTRY
          value: {{ .Values.configMap.bluemixRegistry }}
        - name: BLUEMIX_REGISTRY_NAMESPACE
          value: {{ .Values.configMap.bluemixRegistryNamespace }}
        - name: KUBE_CLUSTER_NAME
          value: {{ .Values.configMap.kubeClusterName }}