apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: bluecompute
    tier: data
    micro: orders
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"

spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: bluecompute
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        tier: data
        micro: orders
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: {{ .Chart.Name }}-mysql
          ports:
            - containerPort: {{ .Values.mysql.service.internalPort }}
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.dbname | quote }}
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.binding.name }}
                  key:  mysqluser
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.binding.name }}
                  key:  mysqlpass
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "false"
          livenessProbe:
            exec:
              command:
              - mysqladmin
              - ping
            initialDelaySeconds: 45
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - mysqladmin
              - ping
            initialDelaySeconds: 15
            timeoutSeconds: 2
      volumes:
        - name: {{ .Chart.Name }}-mysql
          hostPath:
            path: /var/lib/mysql
