# Default values for micro-orders.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: ibmcase/bluecompute-orders
  tag: latest
  pullPolicy: IfNotPresent

hs256key:
  skipDelete: true
  secretName: hs256-key

mysql:
  dbname: ordersdb
  user: dbuser
  password: Pass4dbus3r
  service:
    name: ordersdb
    type: ClusterIP
    externalPort: 3306
    internalPort: 3306
  binding:
    name: binding-orders-mysql
