# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  #repository: registry.csplab.cloudns.cx/microprofile/orders-mp
  repository: ibmcase/orders-mp
  #repository: orders-mp
  tag: v2.0.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 300Mi

service:
  name: orders
  type: NodePort
  servicePort: 9080
  servicePortHttps: 9443
  rabbitmq: rabbitmq
  ordersdb: ordersdb
  inventory: inventory
  auth: auth
  zipkinHost: zipkin
  zipkinPort: 9411

services:
base:
  enabled: false
  replicaCount: 1
  image:
    tag : v0.9.9
  weight: 100

sql:
  user: root
  password: password
  port: 3306

jwt:
  id: myMpJwt

rabbitmq:
  mainPort: 5672
  managePort: 15672
