# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  #repository: registry.csplab.cloudns.cx/microprofile/orders-mp
  repository: ibmcase/orders-mp
  #repository: orders-mp
  tag: v4.0.0
  resources:
    requests:
      cpu: 200m
      memory: 300Mi

service:
  name: orders
  type: NodePort
  servicePort: 9080
  servicePortHttps: 9443
  rabbitmq: rabbitmq
  ordersdb: mariadb
  inventory: inventory
  auth: auth
  zipkinHost: zipkin
  zipkinPort: 9411
  minikubeIp: 10.20.0.169 # Will likely change
  authKubePort: 9443      # Will likely change

services:
base:
  enabled: false
  replicaCount: 1
  image:
    tag : v0.9.9
  weight: 100

sql:
  user: root
  password: password
  port: 3307

mysql:
  image: "mysql"
  imageTag: "5.7.14"
  imagePullPolicy: IfNotPresent

mariadb:
  host: bc-mariadb
  port: 3307
  existingSecret:
  user: root
  password: password
  database: ordersdb

jwt:
  id: myMpJwt

rabbitmq:
  mainPort: 5672
  managePort: 15672

travis: false
jdbcURL: jdbc:mysql://my-release-mysql:3306/ordersdb?useSSL=false