# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  #repository: registry.csplab.cloudns.cx/microprofile/orders-mp
  repository: ibmcase/orders-mp
  #repository: orders-mp
  tag: v4.0.0
  resources:
    requests:
      cpu: 150m
      memory: 64Mi

service:
  name: orders
  type: NodePort
  servicePort: 9080
  servicePortHttps: 9443
  rabbitmq: rabbitmq
  ordersdb: mariadb
  inventory: inventory
  auth: auth
  zipkinHost: zipkin
  zipkinPort: 9411
  minikubeIp:

services:
base:
  enabled: false
  replicaCount: 1
  image:
    tag : v0.9.9
  weight: 100

sql:
  user: root
  password: password
  port: 3307

mysql:
  image: "mysql"
  imageTag: "5.7.14"
  imagePullPolicy: IfNotPresent

mariadb:
  service:
    port: 3307
  rootUser:
    password: password
  db:
    name: ordersdb
    user: dbuser
    password: password
  replication:
    enabled: false
  master:
    persistence:
      enabled: false
    annotations:
    - key: sidecar.istio.io/inject
      value: false
  slave:
    replicas: 1
    persistence:
      enabled: false
    annotations:
    - key: sidecar.istio.io/inject
      value: false
  existingSecret:
  user: root

jwt:
  id: myMpJwt

rabbitmq:
  mainPort: 5672
  managePort: 15672
  epmd: 4369
  dist: 25672

travis: false
authRelease: auth
inventoryRelease: inventory

istio:
  enabled: false
  weight: 100
  mTLS: SIMPLE
  gateway:
    enabled: false
    name:
    hosts:
      - "orders.bluecompute.com"
    TLS:
      enabled: false
      # SIMPLE, MUTUAL
      mode: SIMPLE
      httpsRedirect: false
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      caCertificates: /etc/istio/ingressgateway-ca-certs/ca-chain.cert.pem

ingress:
  enabled: false
  hostname: #orders.bluecompute.com
  path: /micro/orders
  annotations:
    ingress.bluemix.net/redirect-to-https: "True"
  enableTLS: false
  TLS:
  - secretName: orders.bluecompute.com
    hosts:
      - orders.bluecompute.com