apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-create-mysql"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-6"
spec:
  template:
    metadata:
      name: "{{.Release.Name}}-create-mysql"
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
      - name: create-mysql
        image: ibmcase/bluemix-deployer:latest
        command: [ "/bin/bash", "-c" ]
        args: ["source /scripts/bx_login.sh; bx service list | grep compose-for-mysql | grep '^{{ .Values.mysql.serviceName }} ' || bx service create compose-for-mysql {{ .Values.mysql.servicePlan}} {{ .Values.mysql.serviceName }}"]
        imagePullPolicy: Always
        env:
        - name: BX_SPACE
          valueFrom:
            configMapKeyRef:
              name: bluemix-target
              key: bluemix-space
        - name: BX_API_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: bluemix-target
              key: bluemix-api-endpoint
        - name: BLUEMIX_API_KEY
          valueFrom:
            secretKeyRef:
              name: bluemix-api-key
              key: api-key