{{ if not .Values.global.hs256key.secretName }}
apiVersion: v1
data:
  {{if .Values.global.hs256key.secret }}
  key: {{ .Values.global.hs256key.secret | b64enc }}
  {{ else }}
  key: {{ (.Values.hs256key.secret | default (randAlphaNum 256)) | b64enc }}
  {{ end }}
kind: Secret
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: bluecompute
    tier: backend
    micro: orders
  name: "{{ .Chart.Name }}-{{ .Values.hs256key.secretName }}"
  namespace: {{ .Release.Namespace }}
type: Opaque
{{ end }}
