{{- if and (not .Values.mariadb.existingSecret) .Values.mariadb.db.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}-mariadb-secret
  labels:
    chart: '{{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    release: {{ .Release.Name }}
    implementation: microprofile
type: Opaque
data:
  mariadb-password: "{{ .Values.mariadb.db.password | b64enc }}"
{{- end }}
