apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}
  labels:
    {{- include "orders.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.servicePort }}
  - name: https
    port: {{ .Values.service.servicePortHttps }}
  selector:
    {{- include "orders.labels" . | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.name }}
  labels:
    {{- include "orders.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "orders.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "orders.labels" . | indent 8 }}
    spec:
      containers:
      # Liberty Server Container
      - name: "{{ .Chart.Name }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /
            port: 9443
            scheme: HTTPS
          initialDelaySeconds: 30
        livenessProbe:
          httpGet:
            path: /health
            port: 9443
            scheme: HTTPS
          initialDelaySeconds: 1500
          timeoutSeconds: 500

        env:
          {{ if .Values.travis }}
          - name: auth_health
            value: "https://{{ .Values.authRelease }}-{{ .Values.service.auth }}:9443/health"
          - name: inventory_url
            value: "http://{{ .Values.inventoryRelease }}-{{ .Values.service.inventory }}:9080/inventory/rest/inventory/stock"
          - name: inventory_health
            value: "http://{{ .Values.inventoryRelease }}-{{ .Values.service.inventory }}:9080/health"
          - name: jwksUri
            value: "https://{{ .Values.authRelease }}-{{ .Values.service.auth }}:9443/oidc/endpoint/OP/jwk"
          - name: jwksIssuer
            value: "https://{{ .Values.service.minikubeIp }}:9443/oidc/endpoint/OP"
          - name: jwksUser
            value: "user:https://{{ .Values.authRelease }}-{{ .Values.service.auth }}:9443/oidc/endpoint/OP/user"
          - name: administratorRealm
            value: "user:https://{{ .Values.authRelease }}-{{ .Values.service.auth }}:9443/oidc/endpoint/OP/user"          
          {{ else }}
          - name: auth_health
            value: "https://{{ .Release.Name }}-{{ .Values.service.auth }}:9443/health"
          - name: inventory_url
            value: "http://{{ .Release.Name }}-{{ .Values.service.inventory }}:9080/inventory/rest/inventory/stock"
          - name: inventory_health
            value: "http://{{ .Release.Name }}-{{ .Values.service.inventory }}:9080/health"
          - name: jwksUri
            value: "https://{{ .Release.Name }}-{{ .Values.service.auth }}:9443/oidc/endpoint/OP/jwk"
          - name: jwksIssuer
            value: "https://{{ .Release.Name }}-{{ .Values.service.auth }}:9443/oidc/endpoint/OP"
          - name: jwksUser
            value: "user:https://{{ .Release.Name }}-{{ .Values.service.auth }}:9443/oidc/endpoint/OP/user"
          - name: administratorRealm
            value: "user:https://{{ .Release.Name }}-{{ .Values.service.auth }}:9443/oidc/endpoint/OP/user"
          {{ end }}
          - name: jdbcURL
            value: "jdbc:mysql://{{ .Release.Name }}-{{ .Values.service.ordersdb }}:3307/ordersdb?useSSL=false"
          - name: rabbit
            value: "{{ .Release.Name }}-{{ .Values.service.rabbitmq }}"
          - name: PORT
            value: "{{ .Values.service.servicePort }}"
          - name: RELEASE_NAME
            value: "{{ .Release.Name }}"
          - name: jwtid
            value: "{{ .Values.jwt.id }}"
          - name: zipkinHost
            value: "{{ .Release.Name }}-{{ .Values.service.zipkinHost }}"
          - name: zipkinPort
            value: "{{ .Values.service.zipkinPort }}"

        resources:
        {{- include "orders.resources" . | indent 10 }}
        volumeMounts:
        - name: keystorevol
          mountPath: "/etc/keystorevol"
          readOnly: true
      volumes:
      - name: keystorevol
        secret:
          secretName: keystoresecret
