apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Chart.Name}}-bind-messagehub-{{.Release.Name}}-{{ randAlphaNum 5 | lower }}"
  labels:
    app: bluecompute
    micro: orders
    tier: backend
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "27"
spec:
  template:
    metadata:
      name: "{{.Chart.Name}}-bind-messagehub-{{.Release.Name}}-{{ randAlphaNum 5 | lower }}"
      labels:
        app: bluecompute
        micro: orders
        tier: backend
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    spec:
      restartPolicy: Never
      containers:
      - name: bind-messagehub
        image: ibmcase/bluemix-cluster-deployer:latest
        command: [ "/bin/bash", "-c" ]
        args: ["source /scripts/bx_login.sh; bx cs init; bx cs cluster-services ${KUBE_CLUSTER_NAME} | grep '^{{ .Values.messagehub.serviceName }} ' > /dev/null || bx cs cluster-service-bind ${KUBE_CLUSTER_NAME} {{ .Release.Namespace }} '{{ .Values.messagehub.serviceName }}'"]
        imagePullPolicy: IfNotPresent
        env:
        - name: BX_SPACE
          valueFrom:
            configMapKeyRef:
              name: bluemix-target
              key: bluemix-space
        - name: BX_API_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: bluemix-target
              key: bluemix-api-endpoint
        - name: KUBE_CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: bluemix-target
              key: kube-cluster-name
        - name: BLUEMIX_API_KEY
          valueFrom:
            secretKeyRef:
              name: bluemix-api-key
              key: api-key
