apiVersion: v1
kind: Service
metadata:
  name: "rabbitmq-service"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: main
    port: {{ .Values.rabbitmq.mainPort }}
  - name: management
    port: {{ .Values.rabbitmq.managePort }}
  selector:
    micro: orders
    service: chat
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: bluecompute
    micro: orders
    service: chat
    tier: backend
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: bluecompute
        micro: orders
        service: chat
        tier: backend
    spec:
      containers:
      - name: "rabbitmq"
        image: rabbitmq
        imagePullPolicy: Always
