apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.rabbitmq }}
  labels:
    {{- include "orders.labels" . | indent 4 }}
    app.kubernetes.io/name: {{ .Release.Name }}-rabbitmq
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: main
    port: {{ .Values.rabbitmq.mainPort }}
  - name: management
    port: {{ .Values.rabbitmq.managePort }}
  - name: epmd
    port: {{ .Values.rabbitmq.epmd }}
  - name: dist
    port: {{ .Values.rabbitmq.dist }}
  selector:
    {{- include "orders.labels" . | indent 4 }}
    app.kubernetes.io/name: {{ .Release.Name }}-rabbitmq

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.service.rabbitmq }}
  labels:
    {{- include "orders.labels" . | indent 4 }}
    app.kubernetes.io/name: {{ .Release.Name }}-rabbitmq
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "orders.labels" . | indent 6 }}
      app.kubernetes.io/name: {{ .Release.Name }}-rabbitmq
  template:
    metadata:
      labels:
        {{- include "orders.labels" . | indent 8 }}
        app.kubernetes.io/name: {{ .Release.Name }}-rabbitmq
    spec:
      containers:
      - name: "rabbitmq"
        image: rabbitmq
        imagePullPolicy: Always