apiVersion: v1
data:
  key: {{ (.Values.hs256key.secret | default (randAlphaNum 256)) | b64enc }}
kind: Secret
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: bluecompute
    tier: backend
    micro: customer
  name: "{{ .Chart.Name }}-{{ .Values.hs256key.secretName }}"
  namespace: {{ .Release.Namespace }}
type: Opaque