name: ordersdb
version: 0.0.1
appVersion: 1.0.0
description: Fast, reliable, scalable, and easy to use open-source relational database system.
home: https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/tree/microprofile
sources:
  - https://github.com/ibm-cloud-architecture/refarch-cloudnative-micro-orders/tree/microprofile/chart/ordersdb
